//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITkms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public Answers()
        {
            this.AnswerRatings = new HashSet<AnswerRatings>();
        }
    
        public int AnswerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
    
        public virtual ICollection<AnswerRatings> AnswerRatings { get; set; }
        public virtual Questions Questions { get; set; }
        public virtual Users Users { get; set; }
    }
}
