//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITkms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public Articles()
        {
            this.ArticleImages = new HashSet<ArticleImages>();
            this.ArticleRatings = new HashSet<ArticleRatings>();
            this.Questions = new HashSet<Questions>();
            this.Tags = new HashSet<Tags>();
        }

        public Articles(int ArticleID, string Title, string Content) { }
    
        public int ArticleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ArticleCategoryID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string UserIPAddress { get; set; }
    
        public virtual ArticleCategories ArticleCategories { get; set; }
        public virtual ICollection<ArticleImages> ArticleImages { get; set; }
        public virtual ICollection<ArticleRatings> ArticleRatings { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
    }
}
