//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITkms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.AnswerRatings = new HashSet<AnswerRatings>();
            this.Answers = new HashSet<Answers>();
            this.ArticleRatings = new HashSet<ArticleRatings>();
            this.Articles = new HashSet<Articles>();
            this.Questions = new HashSet<Questions>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<AnswerRatings> AnswerRatings { get; set; }
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual ICollection<ArticleRatings> ArticleRatings { get; set; }
        public virtual ICollection<Articles> Articles { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
